/* VOLCADO DE DATOS */

-- Unidades
INSERT INTO UNIDAD VALUES(DEFAULT, 'kilogramos', 1);
INSERT INTO UNIDAD VALUES(DEFAULT, 'libras', 1);
INSERT INTO UNIDAD VALUES(DEFAULT, 'toneladas', 1);
INSERT INTO UNIDAD VALUES(DEFAULT, 'gramos', 1);
INSERT INTO UNIDAD VALUES(DEFAULT, 'unidades', 1);
INSERT INTO UNIDAD VALUES(DEFAULT, 'litros', 1);
INSERT INTO UNIDAD VALUES(DEFAULT, 'galones', 1);
INSERT INTO UNIDAD VALUES(DEFAULT, 'barriles', 1);
INSERT INTO UNIDAD VALUES(DEFAULT, 'latas', 1);
INSERT INTO UNIDAD VALUES(DEFAULT, 'cajas', 1);
INSERT INTO UNIDAD VALUES(DEFAULT, 'metros', 1);

-- Documentos
INSERT INTO DOCUMENTO VALUES(DEFAULT, 'Factura', 1);
INSERT INTO DOCUMENTO VALUES(DEFAULT, 'Ticket', 1);
INSERT INTO DOCUMENTO VALUES(DEFAULT, 'Devolucion', 1);
